//
//package src.sms;
//
//import javax.jws.WebMethod;
//import javax.jws.WebParam;
//import javax.jws.WebResult;
//import javax.jws.WebService;
//import javax.xml.bind.annotation.XmlSeeAlso;
//import javax.xml.ws.RequestWrapper;
//import javax.xml.ws.ResponseWrapper;
//import java.util.List;
//
//
///**
// * This class was generated by the JAX-WS RI.
// * JAX-WS RI 2.2.9-b14002
// * Generated source version: 2.2
// *
// */
//@WebService(name = "psgParlayXSoap", targetNamespace = "http://psg.telia.dk/")
//@XmlSeeAlso({
//    ObjectFactory.class
//})
//public interface PsgParlayXSoap {
//
//
//    /**
//     *
//     * @param addresses
//     * @param senderName
//     * @param charging
//     * @param message
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod(action = "http://psg.telia.dk/sendSms")
//    @WebResult(name = "sendSmsResult", targetNamespace = "http://psg.telia.dk/")
//    @RequestWrapper(localName = "sendSms", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.SendSms")
//    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.SendSmsResponse")
//    public String sendSms(
//            @WebParam(name = "addresses", targetNamespace = "http://psg.telia.dk/")
//                    List<String> addresses,
//            @WebParam(name = "senderName", targetNamespace = "http://psg.telia.dk/")
//                    String senderName,
//            @WebParam(name = "charging", targetNamespace = "http://psg.telia.dk/")
//                    ChargingInformation charging,
//            @WebParam(name = "message", targetNamespace = "http://psg.telia.dk/")
//                    String message);
//
//    /**
//     *
//     * @param validityPeriod
//     * @param addresses
//     * @param senderName
//     * @param protocolId
//     * @param charging
//     * @param udh
//     * @param message
//     * @param dataCodingScheme
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod(action = "http://psg.telia.dk/sendSmsText")
//    @WebResult(name = "sendSmsTextResult", targetNamespace = "http://psg.telia.dk/")
//    @RequestWrapper(localName = "sendSmsText", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.SendSmsText")
//    @ResponseWrapper(localName = "sendSmsTextResponse", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.SendSmsTextResponse")
//    public String sendSmsText(
//            @WebParam(name = "addresses", targetNamespace = "http://psg.telia.dk/")
//                    List<String> addresses,
//            @WebParam(name = "senderName", targetNamespace = "http://psg.telia.dk/")
//                    String senderName,
//            @WebParam(name = "charging", targetNamespace = "http://psg.telia.dk/")
//                    ChargingInformation charging,
//            @WebParam(name = "message", targetNamespace = "http://psg.telia.dk/")
//                    String message,
//            @WebParam(name = "validityPeriod", targetNamespace = "http://psg.telia.dk/")
//                    Integer validityPeriod,
//            @WebParam(name = "udh", targetNamespace = "http://psg.telia.dk/")
//                    String udh,
//            @WebParam(name = "dataCodingScheme", targetNamespace = "http://psg.telia.dk/")
//                    Short dataCodingScheme,
//            @WebParam(name = "protocolId", targetNamespace = "http://psg.telia.dk/")
//                    Short protocolId);
//
//    /**
//     *
//     * @param validityPeriod
//     * @param addresses
//     * @param senderName
//     * @param protocolId
//     * @param charging
//     * @param udh
//     * @param hexData
//     * @param dataCodingScheme
//     * @return
//     *     returns java.lang.String
//     */
//    @WebMethod(action = "http://psg.telia.dk/sendSmsBinary")
//    @WebResult(name = "sendSmsBinaryResult", targetNamespace = "http://psg.telia.dk/")
//    @RequestWrapper(localName = "sendSmsBinary", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.SendSmsBinary")
//    @ResponseWrapper(localName = "sendSmsBinaryResponse", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.SendSmsBinaryResponse")
//    public String sendSmsBinary(
//            @WebParam(name = "addresses", targetNamespace = "http://psg.telia.dk/")
//                    List<String> addresses,
//            @WebParam(name = "senderName", targetNamespace = "http://psg.telia.dk/")
//                    String senderName,
//            @WebParam(name = "charging", targetNamespace = "http://psg.telia.dk/")
//                    ChargingInformation charging,
//            @WebParam(name = "hexData", targetNamespace = "http://psg.telia.dk/")
//                    byte[] hexData,
//            @WebParam(name = "validityPeriod", targetNamespace = "http://psg.telia.dk/")
//                    Integer validityPeriod,
//            @WebParam(name = "udh", targetNamespace = "http://psg.telia.dk/")
//                    String udh,
//            @WebParam(name = "dataCodingScheme", targetNamespace = "http://psg.telia.dk/")
//                    Short dataCodingScheme,
//            @WebParam(name = "protocolId", targetNamespace = "http://psg.telia.dk/")
//                    Short protocolId);
//
//    /**
//     *
//     * @param requestIdentifier
//     * @return
//     *     returns dk.telia.ninja.parlayx.DeliveryInformation
//     */
//    @WebMethod(action = "http://psg.telia.dk/getSmsDeliveryStatus")
//    @WebResult(name = "getSmsDeliveryStatusResult", targetNamespace = "http://psg.telia.dk/")
//    @RequestWrapper(localName = "getSmsDeliveryStatus", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.GetSmsDeliveryStatus")
//    @ResponseWrapper(localName = "getSmsDeliveryStatusResponse", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.GetSmsDeliveryStatusResponse")
//    public DeliveryInformation getSmsDeliveryStatus(
//            @WebParam(name = "requestIdentifier", targetNamespace = "http://psg.telia.dk/")
//                    String requestIdentifier);
//
//    /**
//     *
//     * @param registrationIdentifier
//     * @return
//     *     returns java.util.List<dk.telia.ninja.parlayx.SmsMessage>
//     */
//    @WebMethod(action = "http://psg.telia.dk/getReceivedSms")
//    @WebResult(name = "getReceivedSmsResult", targetNamespace = "http://psg.telia.dk/")
//    @RequestWrapper(localName = "getReceivedSms", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.GetReceivedSms")
//    @ResponseWrapper(localName = "getReceivedSmsResponse", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.GetReceivedSmsResponse")
//    public List<SmsMessage> getReceivedSms(
//            @WebParam(name = "registrationIdentifier", targetNamespace = "http://psg.telia.dk/")
//                    String registrationIdentifier);
//
//    /**
//     *
//     * @param charging
//     * @return
//     *     returns dk.telia.ninja.parlayx.ChargeResult
//     */
//    @WebMethod(action = "http://psg.telia.dk/charge")
//    @WebResult(name = "chargeResult", targetNamespace = "http://psg.telia.dk/")
//    @RequestWrapper(localName = "charge", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.Charge")
//    @ResponseWrapper(localName = "chargeResponse", targetNamespace = "http://psg.telia.dk/", className = "dk.telia.ninja.parlayx.ChargeResponse")
//    public ChargeResult charge(
//            @WebParam(name = "charging", targetNamespace = "http://psg.telia.dk/")
//                    ChargingInformation charging);
//
//}
